project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_TOKEN
base_path: "."
base_url: "https://api.crowdin.com"

files:
  - source: /messages/de.json
    translation: /messages/%two_letters_code%.json
