// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use local SQLite for CLI operations (Prisma CLI doesn't support libsql://)
    // The app uses TURSO_DATABASE_URL at runtime via the libsql adapter
    url: process.env["DATABASE_URL"] || "file:./prisma/dev.db",
  },
});
